[project]
name = "pdf-process"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.5"
dependencies = [
    "flet==0.28.3",
    "flet-desktop>=0.28.3",
    "pypdf2==3.0.1",
]
